knp_translator_get:
    pattern:  /{id}/{domain}/{locale}
    defaults:
        _controller: knp_translator.controller.translator:getAction
        domain: messages
        locale: ~
    requirements: { _method: GET }

knp_translator_put:
    pattern:  /
    defaults:
        _controller: knp_translator.controller.translator:putAction
    requirements: { _method: PUT }

